### ISSUE TITLE
Important ⚠️⚠️⚠️

### ISSUE THREAD

**Issue by TOXIC-DEVIL** [sisula/WhatsBot-COBRA#1]
**Change** the name **WhatsAlexa** from this ropo Its a trade mark name of us and don't be copied ✅️ Please **remove that name from all ropos** or we will take **strick action.** You Must want to remove this **within 24 hrs.. ❌️**

**Comment by sisula** [comment]
ok

**Comment by TOXIC-DEVIL** [comment]
You Must Clear All name 'WhatsAlexa' in ropo

**Comment by TOXIC-DEVIL** [comment]
Still remaining
